### ISSUE TITLE
SSD drive does not mounted

### ISSUE THREAD

**Issue by Remmurt** [nielsmouthaan/ejectify-macos#25] opened 2021-08-07 11:46 UTC
Good day Niels

I have a Satechi hub connected to my MacBook Pro (15-inch, 2018). To it a TimeMachine hard disk (4 TB) Mobile Drive) and an external SSD drive (1 TB/SSD 850 EVO). 
Software is macOS Big Sur 11.5.1 (20G80).

Everything works fine. Only the SSD drive is ejected. However, it is no longer recognized when waking up.

Do you know what could be the reason for this?

Thanks for your feedback.
Paul

**Comment by nielsmouthaan** [comment] 2021-08-08 07:52
Hi Paul,

- Did you disabled the Time Machine disk from ejecting too? Since you're saying only the SSD drive is being ejected.
- What happens when you connect the SSD drive directly to your Mac? Does it remount properly? I want to check if it's the hub that is causing the remounting to fail.

Thanks, Niels.

**Comment by Remmurt** [comment] 2021-08-08 14:10
Hello Niels

Thank you for your feedback.
The Time Machine works perfectly.

The SSD drive was installed in a MacBook Pro.
I then removed it and installed it in a Satechi ALUMINUM TYPE-C HDD / SSD ENCLOSURE bracket. This works when ejected. But the SSD is no longer recognized.

Greetings Paul

**Comment by nielsmouthaan** [comment] 2021-08-10 07:02
This is likely caused by you physically disconnecting the drive (or the hub). Ejectify keeps a reference to the volume in order to mount it again, but physically disconnecting the drive does remove this reference.

What's weird though, is that your Mac doesn't automatically mount the drive after it's physically connected again. This is native behaviour and should simply work, even without Ejectify running. How are you mounting the disk again?

**Comment by nielsmouthaan** [comment] 2022-10-19 09:39
Closing this issue as it's old. Might it be related to this[ planned enhancement/bug issue](https://github.com/nielsmouthaan/ejectify-macos/issues/34)?

**Closed by nielsmouthaan** 2022-10-19 09:39 UTC
Labels: bug
