### ISSUE TITLE
Cannot detect sparse disk image boundle and unmount

### ISSUE THREAD

**Issue by tangdi** [nielsmouthaan/ejectify-macos#27] opened 2021-10-29 07:59 UTC
I have a sparse disk image boundle to store highly sensitive data and I bought the Ejectify hoping to unmount the image boundle when the screen is locked. However, Ejectify **cannot detect** the image boundle when it is mounted. Any clue for that?

**Comment by nielsmouthaan** [comment] 2021-10-30 08:12
So, to confirm: Ejectify doesn't list the volume under the Volumes section? Where do you store the image? On your primary disk?

**Comment by tangdi** [comment] 2021-10-30 14:34
I have the sparse disk image bundle at my Desktop folder and I mount it 
<img width="132" alt="image" src="https://user-images.githubusercontent.com/6425744/139537423-f84e2458-e690-482d-8ac7-8262242ed746.png">

However, Ejectify does not list the volume.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/6425744/139537427-bb3b6175-0d5a-4085-af87-1f85e517ff3a.png">

**Comment by nielsmouthaan** [comment] 2021-10-31 13:10
Make sense, Ejectify [explicitly filters out](https://github.com/nielsmouthaan/ejectify-macos/blob/f90b29687ec7164f5f9868d33f6e538544c7f18b/ejectify/Model/Volume.swift#L84) disk images as it's designed to work with volumes on external disks only (although there's a minor issue causing also internal volumes to be displayed in some cases).

Depending on your coding skills, you could try cloning the repository and removing the indicated if-statement to see if that makes it work for you.

But out of curiosity, why do you want to unmount the volume? Is [FileVault](https://support.apple.com/en-us/HT204837) not already protecting it properly>

**Comment by tangdi** [comment] 2021-11-01 01:13
FileVault only can protect against someone physically pulling out of the disk and try to read it. My scenario is that if someone has a full control of my system, he or she won't notice the disk image into which I can put some highly sensitive data, because the disk image will be unmounted every time laptop sleeps.
Could you add an option to the next version so that although by default it filter out disk image, I can enable this function by using some flag in the official version.

**Comment by nielsmouthaan** [comment] 2022-10-19 09:34
Duplicate of this [planned enhancement ticket](https://github.com/nielsmouthaan/ejectify-macos/issues/36).

**Closed by nielsmouthaan** 2022-10-19 09:34 UTC
Labels: enhancement
